[project]
name = "mta_flask"
version = "0.0.3"
authors = [
  { name="Mark Colby", email="macolby14@gmail.com" },
]
description = "A python webserver that gives NYC MTA times"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
'Flask >= 2.2.2, <3',
'protobuf >= 4.21.12, <5',
'python-dotenv >= 0.21.0, <1',
'requests >= 2.28.1, <3',
]

[project.urls]
"Homepage" = "https://github.com/macolby14/mta-py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
target-version = ['py310']
