name: Build MTA-PY Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Create Build Artifact
        working-directory: ./frontend
        run: |
          npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: |
            ./frontened/build/*
